---
- name: install dependencies
  portage:
    name: "{{ item }}"
    state: present
  with_items: gentoo_package_dependencies

- name: unmask latest ceph
  lineinfile:
    create: yes
    backup: yes
    dest: "/etc/portage/{{ (gentoo_package_keywords == 'package.keywords') | ternary('package.keywords','package.keywords/ceph') }}"
    line: "sys-cluster/ceph ~amd64"
  when: upgrade_ceph_packages

- name: put USE-flags in package.use for ceph
  lineinfile:
    create: yes
    backup: yes
    dest: "/etc/portage/{{ (gentoo_package_use == 'package.use') | ternary('package.use','package.use/ceph') }}"
    line: "sys-cluster/ceph {{ gentoo_use_flags }}"

- name: install ceph
  portage:
    name: "{{ item }}"
    state: present
  with_items: gentoo_ceph_packages
